Fix error
```
[520 / 577] Checking for kmi_symbol_list_strict_mode (arm64_16k;disable_slab_canary;lto=full;notrim) @//aosp:kernel_aarch64_16k; 1s processwrapper-sandbox ... (5 actions running)
ERROR: /src/kernel/aosp/BUILD.bazel:139:22: Checking for kmi_symbol_list_strict_mode (arm64_16k;disable_slab_canary;lto=full;notrim) @//aosp:kernel_aarch64_16k failed: (Exit 1): bash failed: error executing KernelBuildKmiSymbolListStrictMode command (from target //aosp:kernel_aarch64_16k) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Symbols missing from the ksymtab:
  kasan_flag_enabled
```